# SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
# SPDX-License-Identifier: MIT

FROM golang:1.23

RUN go install github.com/sepehrEslami81/webrtc/v4/examples/pion-to-pion/offer@latest

CMD ["offer"]
